### ISSUE TITLE
Using qlot without roswell?

### ISSUE THREAD

**Issue by chaitanyagupta** [fukamachi/qlot#57]
I prefer not to use roswell, is it possible to use qlot without it?

**Comment by fukamachi** [comment]
It's possible since Qlot is a Common Lisp library.

```common-lisp
(ql:quickload :qlot)
(qlot:quickload :yourproject)
```

However, I don't recommend it because it would be trouble when your Lisp environment has installed machine-global Quicklisp, or `~/common-lisp/` directory which will be loaded by ASDF.

Roswell handles _which Quicklisp to load_ before Lisp process will actually be invoked, so it's able to ensure all libraries are loaded from the project-local Quicklisp instead of machine-global ones.

When you really want to do it, do not load machine-global Quicklisp (by like `sbcl --no-init`).

**Comment by chaitanyagupta** [comment]
Thank you @fukamachi! Will try this out.

**Comment by arichiardi** [comment]
Interested in this as well (from a newbie point of view I have so many tools I don't understand that adding roswell would probably not be beneficial).
